HttpServer:
  Port: 9235
  ShutdownTimeout: 2s
Database:
  Main:
    Host: '127.0.0.1'
    Port: '5432'
    User: 'postgres'
    Password:
    Name: 'user'
  Replica:
    Host: '127.0.0.1'
    Port: '5432'
    User: 'postgres'
    Password:
    Name: 'user'