GrpcServer:
  Port: ":9090"
Database:
  Main:
    Host: '127.0.0.1'
    Port: '5432'
    User: 'postgres'
    Password:
    Name: 'user'
  Replica:
    Host: '127.0.0.1'
    Port: '5432'
    User: 'postgres'
    Password:
    Name: 'user'