Auth:
  JWTSecretKey:
HttpServer:
  Port: 9234
  ShutdownTimeout: 2m
Database:
  Main:
    Host: '127.0.0.1'
    Port: '5432'
    User: 'postgres'
    Password:
    Name: 'pickup'
  Replica:
    Host: '127.0.0.1'
    Port: '5432'
    User: 'postgres'
    Password:
    Name: 'pickup'