Auth:
  JWTSecretKey:
  PasswordSecretKey:
HttpServer:
  Port: 9233
  ShutdownTimeout: 2s
Database:
  Main:
    Host: 'localhost'
    Port: '5432'
    User: 'postgres'
    Password:
    Name: 'auth'
  Replica:
    Host: 'localhost'
    Port: '5432'
    User: 'postgres'
    Password:
    Name: 'auth'
Transport:
  UserGrpc:
    Host: localhost:9090
Kafka:
  Brokers:
    - 127.0.0.1:19092
  Producer:
    topic: "user-verification"
  Consumer:
    topics:
      - "user-verification"