Auth:
  JWTSecretKey:
  PasswordSecretKey:
HttpServer:
  Port: 9233
  ShutdownTimeout: 2s
Database:
  Main:
    Host: 'localhost'
    Port: '5432'
    User: 'postgres'
    Password:
    Name: 'auth'
  Replica:
    Host: 'localhost'
    Port: '5432'
    User: 'postgres'
    Password:
    Name: 'auth'
Transport:
  User:
    Host: http://127.0.0.1:9235
    Timeout: 10s